/* eslint-disable max-lines, @typescript-eslint/no-magic-numbers */

/**
 * @fileoverview ESLint configuration for the entire monorepo
 */

import eslint from '@eslint/js';
import * as importX from 'eslint-plugin-import-x';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * ESLint configuration for the entire monorepo
 *
 * @satisfies
 */
export default tseslint.config(
  eslint.configs.recommended,
  tseslint.configs.recommended,
  tseslint.configs.stylistic,
  importX.flatConfigs.typescript,
  {
    ignores: [
      '.next',
      '**/.open-next',
      '.turbo',
      '**/.wrangler',
      'build',
      'dist',
      'node_modules',
      'playwright-report',
      'storybook-static/**',
      'test-results',
      'global.d.ts',
      'junit.xml',
      'lcov.info',
    ],
  },
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.nodeBuiltin,
      },
    },
    rules: {
      /*=================================================== ESLint ===================================================*/
      'array-callback-return': ['error', { allowImplicit: false, allowVoid: true, checkForEach: true }],
      'no-await-in-loop': 'error',
      'no-constructor-return': 'error',
      'no-duplicate-imports': ['error', { includeExports: true }],
      'no-inner-declarations': ['error', 'functions', { blockScopedFunctions: 'disallow' }],
      'no-promise-executor-return': ['error', { allowVoid: false }],
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'error',
      'no-unassigned-vars': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': ['error', { ignore: [] }],
      'no-useless-assignment': 'error',
      'require-atomic-updates': ['error', { allowProperties: false }],

      'accessor-pairs': ['error', { setWithoutGet: true, getWithoutSet: false, enforceForClassMembers: true }],
      'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: true }],
      'block-scoped-var': 'error',
      camelcase: [
        'error',
        {
          properties: 'always',
          ignoreDestructuring: false,
          ignoreImports: false,
          ignoreGlobals: false,
          allow: [],
        },
      ],
      'capitalized-comments': [
        'error',
        'always',
        {
          line: {
            ignoreConsecutiveComments: true,
            ignoreInlineComments: false,
            ignorePattern: 'pragma|ignored',
          },
          block: {
            ignoreConsecutiveComments: false,
            ignoreInlineComments: false,
            ignorePattern: 'pragma|ignored',
          },
        },
      ],
      complexity: ['error', { max: 20, variant: 'modified' }],
      'consistent-return': ['error', { treatUndefinedAsUnspecified: false }],
      'consistent-this': ['error', 'that'],
      curly: ['error', 'all'],
      'default-case': ['error', { commentPattern: '/^No Default$/i' }],
      'default-case-last': 'error',
      eqeqeq: ['error', 'smart'],
      'func-name-matching': [
        'error',
        'always',
        {
          considerPropertyDescriptor: false,
          includeCommonJSModuleExports: false,
        },
      ],
      'func-names': ['error', 'always', { generators: 'always' }],
      'func-style': [
        'error',
        'expression',
        {
          allowArrowFunctions: true,
          allowTypeAnnotation: false,
          overrides: { namedExports: 'expression' },
        },
      ],
      'grouped-accessor-pairs': ['error', 'getBeforeSet'],
      'guard-for-in': 'error',
      'id-denylist': ['error', 'cb', 'e', 'err', 'ev'],
      'id-length': ['error', { min: 2, max: Infinity, properties: 'always', exceptions: [], exceptionPatterns: [] }],
      'logical-assignment-operators': ['error', 'always', { enforceForIfStatements: true }],
      'max-classes-per-file': ['error', { max: 1, ignoreExpressions: false }],
      'max-depth': ['error', { max: 4 }],
      'max-lines': ['error', { max: 300, skipBlankLines: true, skipComments: true }],
      'max-lines-per-function': ['error', { max: 50, skipBlankLines: true, skipComments: true, IIFEs: false }],
      'max-nested-callbacks': ['error', { max: 10 }],
      'max-statements': ['error', 30, { ignoreTopLevelFunctions: false }],
      'new-cap': [
        'error',
        {
          newIsCap: true,
          capIsNew: true,
          newIsCapExceptions: [],
          capIsNewExceptions: [],
          newIsCapExceptionPattern: '',
          capIsNewExceptionPattern: '',
          properties: true,
        },
      ],
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': ['error', { allow: [], int32Hint: true }],
      'no-caller': 'error',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      'no-continue': 'error',
      'no-div-regex': 'error',
      'no-else-return': ['error', { allowElseIf: true }],
      'no-eq-null': 'error',
      'no-eval': ['error', { allowIndirect: false }],
      'no-extend-native': ['error', { exceptions: [] }],
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-implicit-coercion': [
        'error',
        {
          boolean: true,
          number: true,
          string: true,
          disallowTemplateShorthand: true,
          allow: [],
        },
      ],
      'no-implicit-globals': ['error', { lexicalBindings: false }],
      'no-implied-eval': 'error',
      'no-invalid-this': ['error', { capIsConstructor: false }],
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-multi-assign': ['error', { ignoreNonDeclaration: false }],
      'no-multi-str': 'error',
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': [
        'error',
        {
          props: true,
          ignorePropertyModificationsFor: [],
          ignorePropertyModificationsForRegex: [],
        },
      ],
      'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
      'no-proto': 'error',
      'no-restricted-exports': [
        'error',
        {
          restrictedNamedExports: [],
          restrictedNamedExportsPattern: '',
          restrictDefaultExports: {
            direct: false,
            named: false,
            defaultFrom: false,
            namedFrom: false,
            namespaceFrom: false,
          },
        },
      ],
      'no-restricted-globals': [
        'error',
        { name: 'event', message: 'Use local parameter instead.' },
        { name: 'fdescribe', message: 'Do not commit focused tests.' },
        { name: 'fit', message: 'Do not commit focused tests.' },
        { name: 'xdescribe', message: 'Do not commit skipped tests.' },
        { name: 'xit', message: 'Do not commit skipped tests.' },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'BinaryExpression[operator="in"]',
          message: 'Use `hasOwnProperty` instead.',
        },
        {
          selector: 'CallExpression[callee.name="setInterval"][arguments.length!=2]',
          message: 'setInterval must always be invoked with two arguments.',
        },
        {
          selector: 'CallExpression[callee.name="setTimeout"][arguments.length!=2]',
          message: 'setTimeout must always be invoked with two arguments.',
        },
        {
          selector: 'FunctionExpression',
          message: 'Use arrow function instead.',
        },
        {
          selector: 'WithStatement',
          message: 'Use `await` instead.',
        },
      ],
      'no-return-assign': ['error', 'except-parens'],
      'no-script-url': 'error',
      'no-sequences': ['error', { allowInParentheses: true }],
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-underscore-dangle': [
        'error',
        {
          allow: [],
          allowAfterThis: false,
          allowAfterSuper: false,
          allowAfterThisConstructor: false,
          enforceInMethodNames: true,
          enforceInClassFields: true,
          allowInArrayDestructuring: false,
          allowInObjectDestructuring: false,
          allowFunctionParams: true,
        },
      ],
      'no-unneeded-ternary': ['error', { defaultAssignment: true }],
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: false,
          allowTernary: false,
          allowTaggedTemplates: false,
          enforceForJSX: true,
          ignoreDirectives: false,
        },
      ],
      'no-useless-call': 'error',
      'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
      'no-useless-concat': 'error',
      'no-useless-rename': ['error', { ignoreImport: false, ignoreExport: false, ignoreDestructuring: false }],
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': ['error', { allowAsStatement: false }],
      'no-warning-comments': [
        'error',
        {
          terms: ['TODO', 'FIXME', 'XXX'],
          location: 'start',
          decoration: ['/', '*', '='],
        },
      ],
      'object-shorthand': [
        'error',
        'always',
        {
          avoidQuotes: false,
          ignoreConstructors: false,
          methodsIgnorePattern: '',
          avoidExplicitReturnArrows: true,
        },
      ],
      'one-var': ['error', { var: 'never', let: 'never', const: 'never', separateRequires: true }],
      'operator-assignment': ['error', 'always'],
      'prefer-arrow-callback': ['error', { allowNamedFunctions: false, allowUnboundThis: true }],
      'prefer-const': ['error', { destructuring: 'any', ignoreReadBeforeAssign: false }],
      'prefer-exponentiation-operator': 'error',
      'prefer-named-capture-group': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-object-has-own': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: false }],
      'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      radix: ['error', 'as-needed'],
      'require-await': 'error',
      'require-unicode-regexp': ['error', { requireFlag: 'v' }],
      'sort-vars': ['error', { ignoreCase: false }],
      strict: ['error', 'safe'],
      'symbol-description': 'error',
      'vars-on-top': 'error',
      yoda: ['error', 'never', { exceptRange: false, onlyEquality: false }],

      'unicode-bom': ['error', 'never'],

      /*============================================= @typescript-eslint =============================================*/
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/array-type': ['error', { default: 'generic', readonly: 'generic' }],
      '@typescript-eslint/ban-tslint-comment': 'error',
      '@typescript-eslint/class-literal-property-style': ['error', 'fields'],
      '@typescript-eslint/class-methods-use-this': [
        'error',
        {
          enforceForClassFields: true,
          ignoreClassesThatImplementAnInterface: false,
          ignoreOverrideMethods: false,
          exceptMethods: [],
        },
      ],
      '@typescript-eslint/consistent-generic-constructors': ['error', 'type-annotation'],
      '@typescript-eslint/consistent-indexed-object-style': ['error', 'record'],
      '@typescript-eslint/consistent-type-assertions': [
        'error',
        {
          assertionStyle: 'as',
          arrayLiteralTypeAssertions: 'allow',
          objectLiteralTypeAssertions: 'allow',
        },
      ],
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/default-param-last': 'error',
      '@typescript-eslint/explicit-function-return-type': [
        'error',
        {
          allowConciseArrowFunctionExpressionsStartingWithVoid: false,
          allowDirectConstAssertionInArrowFunctions: true,
          allowExpressions: false,
          allowFunctionsWithoutTypeParameters: false,
          allowHigherOrderFunctions: true,
          allowIIFEs: false,
          allowTypedFunctionExpressions: true,
          allowedNames: [],
        },
      ],
      '@typescript-eslint/explicit-member-accessibility': [
        'error',
        {
          accessibility: 'explicit',
          ignoredMethodNames: [],
          overrides: {
            accessors: 'explicit',
            constructors: 'explicit',
            methods: 'explicit',
            parameterProperties: 'explicit',
            properties: 'explicit',
          },
        },
      ],
      '@typescript-eslint/explicit-module-boundary-types': [
        'error',
        {
          allowArgumentsExplicitlyTypedAsAny: false,
          allowDirectConstAssertionInArrowFunctions: true,
          allowHigherOrderFunctions: true,
          allowOverloadFunctions: false,
          allowTypedFunctionExpressions: true,
          allowedNames: [],
        },
      ],
      '@typescript-eslint/init-declarations': ['error', 'always'],
      '@typescript-eslint/max-params': ['error', { countVoidThis: false, max: 3 }],
      '@typescript-eslint/member-ordering': [
        'error',
        {
          default: {
            optionalityOrder: 'required-first',
            order: 'as-written',
            memberTypes: [
              'signature',
              'call-signature',
              'public-static-field',
              'protected-static-field',
              'private-static-field',
              '#private-static-field',
              'public-decorated-field',
              'protected-decorated-field',
              'private-decorated-field',
              'public-instance-field',
              'protected-instance-field',
              'private-instance-field',
              '#private-instance-field',
              'public-abstract-field',
              'protected-abstract-field',
              'public-field',
              'protected-field',
              'private-field',
              '#private-field',
              'static-field',
              'instance-field',
              'abstract-field',
              'decorated-field',
              'field',
              'static-initialization',
              'public-constructor',
              'protected-constructor',
              'private-constructor',
              'constructor',
              'public-static-accessor',
              'protected-static-accessor',
              'private-static-accessor',
              '#private-static-accessor',
              'public-decorated-accessor',
              'protected-decorated-accessor',
              'private-decorated-accessor',
              'public-instance-accessor',
              'protected-instance-accessor',
              'private-instance-accessor',
              '#private-instance-accessor',
              'public-abstract-accessor',
              'protected-abstract-accessor',
              'public-accessor',
              'protected-accessor',
              'private-accessor',
              '#private-accessor',
              'static-accessor',
              'instance-accessor',
              'abstract-accessor',
              'decorated-accessor',
              'accessor',
              'public-static-get',
              'protected-static-get',
              'private-static-get',
              '#private-static-get',
              'public-decorated-get',
              'protected-decorated-get',
              'private-decorated-get',
              'public-instance-get',
              'protected-instance-get',
              'private-instance-get',
              '#private-instance-get',
              'public-abstract-get',
              'protected-abstract-get',
              'public-get',
              'protected-get',
              'private-get',
              '#private-get',
              'static-get',
              'instance-get',
              'abstract-get',
              'decorated-get',
              'get',
              'public-static-set',
              'protected-static-set',
              'private-static-set',
              '#private-static-set',
              'public-decorated-set',
              'protected-decorated-set',
              'private-decorated-set',
              'public-instance-set',
              'protected-instance-set',
              'private-instance-set',
              '#private-instance-set',
              'public-abstract-set',
              'protected-abstract-set',
              'public-set',
              'protected-set',
              'private-set',
              '#private-set',
              'static-set',
              'instance-set',
              'abstract-set',
              'decorated-set',
              'set',
              'public-static-method',
              'protected-static-method',
              'private-static-method',
              '#private-static-method',
              'public-decorated-method',
              'protected-decorated-method',
              'private-decorated-method',
              'public-instance-method',
              'protected-instance-method',
              'private-instance-method',
              '#private-instance-method',
              'public-abstract-method',
              'protected-abstract-method',
              'public-method',
              'protected-method',
              'private-method',
              '#private-method',
              'static-method',
              'instance-method',
              'abstract-method',
              'decorated-method',
              'method',
            ],
          },
        },
      ],
      '@typescript-eslint/method-signature-style': ['error', 'property'],
      '@typescript-eslint/no-confusing-non-null-assertion': 'error',
      '@typescript-eslint/no-dynamic-delete': 'error',
      '@typescript-eslint/no-empty-function': ['error', { allow: [] }],
      '@typescript-eslint/no-extraneous-class': [
        'error',
        {
          allowConstructorOnly: false,
          allowEmpty: false,
          allowStaticOnly: false,
          allowWithDecorator: false,
        },
      ],
      '@typescript-eslint/no-import-type-side-effects': 'error',
      '@typescript-eslint/no-inferrable-types': ['error', { ignoreParameters: false, ignoreProperties: false }],
      '@typescript-eslint/no-invalid-void-type': [
        'error',
        { allowAsThisParameter: false, allowInGenericTypeArguments: true },
      ],
      '@typescript-eslint/no-loop-func': 'error',
      '@typescript-eslint/no-magic-numbers': [
        'error',
        {
          detectObjects: false,
          enforceConst: true,
          ignoreArrayIndexes: false,
          ignoreClassFieldInitialValues: false,
          ignoreDefaultValues: false,
          ignoreEnums: false,
          ignoreNumericLiteralTypes: false,
          ignoreReadonlyClassProperties: false,
          ignoreTypeIndexes: false,
          ignore: [],
        },
      ],
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-restricted-imports': ['error', { paths: [], patterns: [] }],
      '@typescript-eslint/no-restricted-types': 'error',
      '@typescript-eslint/no-shadow': [
        'error',
        {
          builtinGlobals: true,
          ignoreOnInitialization: false,
          ignoreFunctionTypeParameterNameValueShadow: true,
          ignoreTypeValueShadow: true,
          hoist: 'functions-and-types',
          allow: ['resolve', 'reject', 'done', 'cb'],
        },
      ],
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': 'error',
      '@typescript-eslint/no-use-before-define': [
        'error',
        {
          allowNamedExports: false,
          classes: true,
          enums: true,
          functions: true,
          ignoreTypeReferences: false,
          typedefs: true,
          variables: true,
        },
      ],
      '@typescript-eslint/no-useless-constructor': 'error',
      '@typescript-eslint/no-useless-empty-export': 'error',
      '@typescript-eslint/parameter-properties': ['error', { prefer: 'class-property', allow: [] }],
      '@typescript-eslint/prefer-enum-initializers': 'error',
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/prefer-function-type': 'error',
      '@typescript-eslint/prefer-literal-enum-member': ['error', { allowBitwiseExpressions: false }],
      '@typescript-eslint/typedef': [
        'error',
        {
          arrayDestructuring: false,
          arrowParameter: true,
          memberVariableDeclaration: true,
          objectDestructuring: false,
          parameter: true,
          propertyDeclaration: true,
          variableDeclaration: true,
          variableDeclarationIgnoreFunction: true,
        },
      ],
      '@typescript-eslint/unified-signatures': ['error', { ignoreDifferentlyNamedParameters: false }],

      /*=========================================== eslint-plugin-import-x ===========================================*/
      'import-x/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'import-x/exports-last': 'error',
      'import-x/first': 'error',
      'import-x/group-exports': 'error',
      'import-x/max-dependencies': ['error', { max: 10, ignoreTypeImports: false }],
      'import-x/newline-after-import': ['error', { count: 1, exactCount: true, considerComments: true }],
      'import-x/no-absolute-path': ['error', { esmodule: true, commonjs: true, amd: true }],
      'import-x/no-amd': 'error',
      'import-x/no-commonjs': [
        'error',
        {
          allowRequire: false,
          allowConditionalRequire: false,
          allowPrimitiveModules: false,
        },
      ],
      'import-x/no-cycle': [
        'error',
        {
          allowUnsafeDynamicCyclicDependency: false,
          ignoreExternal: false,
          maxDepth: Infinity,
        },
      ],
      'import-x/no-deprecated': 'error',
      'import-x/no-dynamic-require': 'error',
      'import-x/no-empty-named-blocks': 'error',
      'import-x/no-extraneous-dependencies': [
        'error',
        {
          devDependencies: true,
          optionalDependencies: true,
          peerDependencies: true,
          bundledDependencies: true,
          includeInternal: false,
          includeTypes: false,
          whitelist: [],
        },
      ],
      'import-x/no-import-module-exports': ['error', { exceptions: [] }],
      'import-x/no-mutable-exports': 'error',
      'import-x/no-named-default': 'error',
      'import-x/no-self-import': 'error',
      'import-x/no-unassigned-import': ['error', { allow: [] }],
      'import-x/no-useless-path-segments': ['error', { noUselessIndex: true }],
      'import-x/no-webpack-loader-syntax': 'error',
      'import-x/order': [
        'error',
        {
          'newlines-between': 'always',
          warnOnUnassignedImports: true,
          alphabetize: { caseInsensitive: true, order: 'asc' },
          groups: ['builtin', 'external', 'internal', ['sibling', 'parent'], 'index', 'unknown'],
        },
      ],
      'import-x/prefer-default-export': ['error', { target: 'single' }],

      /*================================================== Disabled ==================================================*/
      // Disabled in favor of `@typescript-eslint` rules
      'class-methods-use-this': 'off',
      'default-param-last': 'off',
      'dot-notation': 'off',
      'init-declarations': 'off',
      'max-params': 'off',
      'no-empty-function': 'off',
      'no-loop-func': 'off',
      'no-magic-numbers': 'off',
      'no-restricted-imports': 'off',
      'no-shadow': 'off',
      'no-use-before-define': 'off',
      'no-useless-constructor': 'off',
      'prefer-destructuring': 'off',

      'no-ternary': 'off', // Too strict and can be useful for readability
      'sort-imports': 'off', // Handled by `eslint-plugin-import-x`
      'sort-keys': 'off', // Too strict and can be useful for readability

      'import-x/namespace': 'off', // False positives and performance issues
      'import-x/no-named-as-default-member': 'off', // Too strict and can be useful for readability
      'import-x/no-unresolved': 'off', // Handled by TypeScript
    },
  }
);
