packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ~9.35.0
  '@opennextjs/cloudflare': ^1.8.1
  '@playwright/test': ^1.55.0
  '@tailwindcss/postcss': ~4.1.13
  '@testing-library/react': ~16.3.0
  '@testing-library/user-event': ~14.6.1
  '@types/mdx': ^2.0.13
  '@types/node': 22.18.1
  '@types/react': ^19.1.12
  '@types/semver': ~7.7.1
  classnames: ~2.5.1
  cross-env: ^10.0.0
  eslint: ~9.35.0
  eslint-config-next: 15.5.2
  eslint-import-resolver-typescript: ~4.4.4
  eslint-plugin-import-x: ~4.16.1
  eslint-plugin-mdx: ~3.6.2
  eslint-plugin-react: ~7.37.5
  eslint-plugin-react-hooks: 5.2.0
  prettier: 3.6.2
  prettier-plugin-tailwindcss: 0.6.14
  react: ^19.1.1
  react-dom: ^19.1.1
  stylelint: 16.24.0
  stylelint-config-standard: 39.0.0
  stylelint-order: 7.0.0
  tailwindcss: ~4.1.13
  typescript: ~5.9.2
  typescript-eslint: ~8.43.0
  wrangler: ^4.40.2

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
