packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ~9.39.1
  '@opennextjs/cloudflare': ^1.14.3
  '@playwright/test': ^1.57.0
  '@tailwindcss/postcss': ~4.1.17
  '@testing-library/react': ~16.3.0
  '@testing-library/user-event': ~14.6.1
  '@types/mdx': ^2.0.13
  '@types/node': 22.19.1
  '@types/react': ^19.2.7
  '@types/semver': ~7.7.1
  classnames: ~2.5.1
  cross-env: ^10.1.0
  eslint: ~9.39.1
  eslint-config-next: 16.0.7
  eslint-import-resolver-typescript: ~4.4.4
  eslint-plugin-import-x: ~4.16.1
  eslint-plugin-mdx: ~3.6.2
  eslint-plugin-react: ~7.37.5
  eslint-plugin-react-hooks: 7.0.1
  prettier: 3.7.4
  prettier-plugin-tailwindcss: 0.7.2
  react: ^19.2.1
  react-dom: ^19.2.1
  stylelint: 16.26.1
  stylelint-config-standard: 39.0.1
  stylelint-order: 7.0.0
  tailwindcss: ~4.1.17
  typescript: ~5.9.3
  typescript-eslint: ~8.48.1
  wrangler: ^4.53.0

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
